POST http://localhost:4005/app/signup
Content-Type: application/json

{
    "pickup":"Chennai",
    "drop":"Kanyakumari",
    "gender":"Male",
    "idType":"Aadhaar",
    "idCard":"12345abc",
    "name":"Uthaya",
    "email":"uthaya19052002@gmail.com",
    "contact":"8438534644",
    "age":"22"
}